<?php

namespace AppBundle\Repository;

/**
 * DowntimePeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DowntimePeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
