<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * DowntimePeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DowntimePeriodRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Gets all downtime periods that a particular User has characters for (a player)
     */     
    public function findAllByPlayer(User $player) {
        //TODO
        $player_id = $player->getId();
        return $this->getEntityManager()
            ->createQueryBuilder('d')
            ->select('d')
            ->from('AppBundle:DowntimePeriod','d')
            ->innerJoin('d.game', 'g')
            ->innerJoin('g.characters', 'c')
            ->where('c.player = :player')
            ->setParameter('player', $player)
            ->getQuery()
            ->getResult();
    }
}
