<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use AppBundle\Entity\Game;
use AppBundle\Entity\Member;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByUser(User $user) {
        $user_id = $user->getId();
        return $this->getEntityManager()
            ->createQueryBuilder('g')
            ->select('g')
            ->from('AppBundle:Game','g')
            ->innerJoin('g.members', 'm')
            ->where('m.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }

    public function findAllByUserAndPosition(User $user, $position) {
        $user_id = $user->getId();
        return $this->getEntityManager()
            ->createQueryBuilder('g')
            ->select('g')
            ->from('AppBundle:Game','g')
            ->innerJoin('g.members', 'm')
            ->where('m.user = :user')
            ->andWhere('m.position = :position')
            ->setParameter('user', $user)
            ->setParameter('position', $position)
            ->getQuery()
            ->getResult();
    }
}
