<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use AppBundle\Entity\Game;
use AppBundle\Entity\Member;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByUser(User $user) {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('g')
            ->from('AppBundle:Game','g')
            ->innerJoin('g', 'AppBundle:Member', 'm', 'g.id = m.game_id')
            ->getQuery()
            ->getResult();
    }
}
