<?php

namespace AppBundle\Repository;

use AppBundle\Entity\DowntimePeriod;
use AppBundle\Entity\Character;


/**
 * TurnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByPeriodAndCharacter(DowntimePeriod $period, Character $character) {
        return $this->getEntityManager()
            ->createQueryBuilder('t')
            ->select('t')
            ->from('AppBundle:Turn','t')            
            ->where('t.downtimePeriod = :period')
            ->where('t.characte = :character')
            ->setParameter('character', $character)
            ->getQuery()
            ->getResult();
    }
}
