<?php

namespace AppBundle\Repository;

/**
 * TurnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnRepository extends \Doctrine\ORM\EntityRepository
{
}
